name: Update CMS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-cms:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-liberation
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "WordCloud dependencies failed, will use CSS fallback"
        
    - name: Generate CMS files
      run: python generate_cms.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html posts.json categories.json
        git diff --staged --quiet || git commit -m "Auto-update CMS files with word cloud"
        git push
